[package]
name = "rocksdb-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cxx-build = "1.0.95"

[dependencies]
cxx = "1.0.95"
paste = "1.0.12"
