name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ${{github.workspace}}/rocksdb/rocksdb-sys
      run: cargo build --verbose
    - name: Run tests
      working-directory: ${{github.workspace}}/rocksdb/rocksdb-sys
      run: cargo test --verbose
